apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceuser
  namespace: oldgeneral
spec:
  selector:
    matchLabels:
      app: serviceuser
  template:
    metadata:
      labels:
        app: serviceuser
    spec:
      containers:
        - name: serviceuser
          image: swr.cn-north-4.myhuaweicloud.com/oldgeneral/serviceuser:nightly
          resources:
          ports:
            - containerPort: 30001
          env:
            - name: ListenPort
              value: ":30001"
            - name: DB_USER
              value: caocao
            - name: DB_ADDRESS
              value: mysql.database.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: oldgeneral
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user_password
---
apiVersion: v1
kind: Service
metadata:
  name: serviceuser
  namespace: oldgeneral
spec:
  selector:
    app: serviceuser
  ports:
    - port: 30001
      targetPort: 30001
      protocol: TCP
  type: ClusterIP
