trigger:
  branches:
    include:
    - main
    - release*
  paths:
    exclude:
    - docs
    - README*
    - LICENSE
    - .github
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - main
    - release*
  paths:
    exclude:
    - docs
    - README*
    - LICENSE
    - .github
stages:
  - stage: go_test_and_kind_e2e_test
    jobs:
    - job: go_build_and_test
      steps:
        - task: GoTool@0
          inputs:
            version: '1.19.2'
        - script: |
            make test
          displayName: "go test"
