
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs
    - LICENSE
    - .github
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs
    - LICENSE
    - .github


pool:
   vmImage: 'ubuntu-latest'

stages:
- stage: go_test
  jobs:
  - job: go_build_and_test
    steps:
    - task: GoTool@0
      inputs:
        version: '1.19.2'
    - task: Go@0
      inputs:
        command: 'mod'
        arguments: 'download'
    - script: |
        make test
