apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceiam
  namespace: oldgeneral
spec:
  selector:
    matchLabels:
      app: serviceiam
  template:
    metadata:
      labels:
        app: serviceiam
    spec:
      containers:
        - name: serviceiam
          image: swr.cn-north-4.myhuaweicloud.com/oldgeneral/serviceiam:nightly
          resources:
          ports:
            - containerPort: 30001
          env:
            - name: ListenPort
              value: ":30001"
            - name: DB_USER
              value: caocao
            - name: DB_ADDRESS
              value: mysql.database.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: oldgeneral
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: serviceiam
  namespace: oldgeneral
spec:
  selector:
    app: serviceiam
  ports:
    - port: 30001
      targetPort: 30001
      protocol: TCP
  type: ClusterIP
