name: CodeCov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19.2'
    - name: Run coverage
      run: make test
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
          files: ./coverage.out
          name: codecov
          fail_ci_if_error: true
          verbose: true