name: Build and push Docker image using Buildx

on:
  push:
    paths-ignore:
      - "deployment/**"
      - "docs/**"
      - "README.md"
    branches:
      - main

env:
  DOCKER_REGISTRY: swr.cn-north-4.myhuaweicloud.com/oldgeneral

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Installing protobuf dependencies
        run: |
          make install-dependencies

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY }}
      - name: Build and push Docker image
        run: |
          make build-protos-go
          make build-image
          docker tag serviceapi:nightly ${{ env.DOCKER_REGISTRY }}/serviceapi:${{ github.run_id }}
          docker push ${{ env.DOCKER_REGISTRY }}/serviceapi:${{ github.run_id }}
          docker tag serviceiam:nightly ${{ env.DOCKER_REGISTRY }}/serviceiam:${{ github.run_id }}
          docker push ${{ env.DOCKER_REGISTRY }}/serviceiam:${{ github.run_id }}

      - name: Patch ServiceAPI Image tag
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: set image deployment -n oldgeneral serviceapi serviceapi=${{ env.DOCKER_REGISTRY }}/serviceapi:${{ github.run_id }}
      - name: Patch ServiceIAM Image tag
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: set image deployment -n oldgeneral serviceiam serviceiam=${{ env.DOCKER_REGISTRY }}/serviceiam:${{ github.run_id }}
